# Generated by Django 6.0.2 on 2026-03-29 13:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('quantite_stock', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Piece',
                'verbose_name_plural': 'Pieces',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('receptioniste', 'Receptioniste'), ('manager', 'Manager'), ('technicien', 'Technicien'), ('chefstock', 'ChefStock'), ('admin', 'Administrateur')], max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DemandeMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorite', models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('haute', 'Haute')], default='moyenne', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_manager', to=settings.AUTH_USER_MODEL)),
                ('receptioniste', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_reception', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de maintenance',
                'verbose_name_plural': 'Demandes de maintenance',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.TextField(blank=True, null=True)),
                ('solution_proposee', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intervention', to='users.demandemaintenance')),
                ('technicien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='FicheReparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_panne', models.TextField()),
                ('solution', models.TextField(blank=True, null=True)),
                ('cout_main_oeuvre', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('confirmation', models.BooleanField(default=False)),
                ('valide_manager', models.BooleanField(default=False)),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_reparation', to='users.intervention')),
            ],
            options={
                'verbose_name': 'Fiche de réparation',
                'verbose_name_plural': 'Fiches de réparation',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('est_payee', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='users.client')),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='users.intervention')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('etat', models.CharField(default='Reçu', max_length=100)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='users.client')),
            ],
            options={
                'verbose_name': 'Materiel',
                'verbose_name_plural': 'Materiels',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.AddField(
            model_name='demandemaintenance',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='users.materiel'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(blank=True, max_length=200)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement')], default='especes', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='users.facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='DemandePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('statut', models.CharField(choices=[('demandee', 'Demandée'), ('approuvee', 'Approuvée'), ('livree', 'Livrée')], default='demandee', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_pieces', to='users.fichereparation')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='users.piece')),
            ],
            options={
                'verbose_name': 'Demande de piece',
                'verbose_name_plural': 'Demandes de pieces',
            },
        ),
    ]
