# Generated by Django 6.0.2 on 2026-04-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_administrateur_chefstock_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categorie materiel',
                'verbose_name_plural': 'Categories materiel',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='piece',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='users.categoriemateriel'),
        ),
    ]
