# Generated by Django 6.0.2 on 2026-05-12 17:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fix_piece_categorie_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('pays', models.CharField(blank=True, default='Maroc', max_length=100, null=True)),
                ('contact_principal', models.CharField(blank=True, max_length=200, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='piece',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piece',
            name='modele',
            field=models.CharField(blank=True, help_text='Modèle de la pièce', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence/SKU de la pièce', max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CommandePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(db_index=True, max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('commande', 'Commandée'), ('livree', 'Livrée'), ('rejetee', 'Rejetée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison_prevue', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('chef_stock', models.ForeignKey(blank=True, limit_choices_to={'role': 'chefstock'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_creees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='users.fournisseur')),
            ],
            options={
                'verbose_name': 'Commande de pièces',
                'verbose_name_plural': 'Commandes de pièces',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommandePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sous_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='users.commandepiece')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='users.piece')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
        migrations.CreateModel(
            name='PrixFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delai_livraison_jours', models.IntegerField(blank=True, help_text='Délai de livraison en jours', null=True)),
                ('quantite_minimum', models.IntegerField(default=1, help_text='Quantité minimum pour cette offre')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_pieces', to='users.fournisseur')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_fournisseurs', to='users.piece')),
            ],
            options={
                'verbose_name': 'Prix fournisseur',
                'verbose_name_plural': 'Prix fournisseurs',
                'ordering': ['piece', 'prix'],
                'unique_together': {('piece', 'fournisseur')},
            },
        ),
    ]
