# Generated by Django 6.0.2 on 2026-05-19 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_fournisseur_piece_date_creation_piece_modele_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandepiece',
            name='date_reponse_fournisseur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandepiece',
            name='motif_refus_fournisseur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandepiece',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_pieces', to='users.commandepiece'),
        ),
        migrations.AddField(
            model_name='demandepiece',
            name='date_reponse_fournisseur',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandepiece',
            name='demandeur_stock',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'chefstock'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_pieces_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demandepiece',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_pieces', to='users.fournisseur'),
        ),
        migrations.AddField(
            model_name='demandepiece',
            name='motif_refus_fournisseur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandepiece',
            name='prix_propose_fournisseur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='demandepiece',
            name='quantite_manquante',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piece',
            name='seuil_alerte',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='piece',
            name='statut_stock',
            field=models.CharField(choices=[('en_stock', 'En stock'), ('stock_faible', 'Stock faible'), ('hors_stock', 'Hors stock')], db_index=True, default='en_stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='commandepiece',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente_fournisseur', 'En attente fournisseur'), ('acceptee_fournisseur', 'Acceptée fournisseur'), ('refusee_fournisseur', 'Refusée fournisseur'), ('commande', 'Commandée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='brouillon', max_length=30),
        ),
        migrations.AlterField(
            model_name='demandepiece',
            name='statut',
            field=models.CharField(choices=[('demandee', 'Demandée'), ('en_attente_fournisseur', 'En attente fournisseur'), ('acceptee_fournisseur', 'Acceptée fournisseur'), ('refusee_fournisseur', 'Refusée fournisseur'), ('reaffectee', 'Réaffectée à un autre fournisseur'), ('commandee', 'Commandée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='demandee', max_length=30),
        ),
        migrations.CreateModel(
            name='FactureFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(db_index=True, max_length=100, unique=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('validee', 'Validée'), ('payee', 'Payée')], default='brouillon', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture_fournisseur', to='users.commandepiece')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='users.fournisseur')),
            ],
            options={
                'verbose_name': 'Facture fournisseur',
                'verbose_name_plural': 'Factures fournisseurs',
                'ordering': ['-date_facture'],
            },
        ),
    ]
