# Generated by Django 6.0.2 on 2026-05-19 21:52

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_commandepiece_date_reponse_fournisseur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FournisseurUser',
            fields=[
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='utilisateur',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'fournisseur'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('receptioniste', 'Receptioniste'), ('manager', 'Manager'), ('technicien', 'Technicien'), ('chefstock', 'ChefStock'), ('fournisseur', 'Fournisseur'), ('admin', 'Administrateur')], max_length=20),
        ),
    ]
