# Generated by Django 6.0.2 on 2026-06-02 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_fournisseuruser_fournisseur_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepiece',
            name='fiche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_pieces', to='users.fichereparation'),
        ),
    ]
