# Generated by Django 6.0.2 on 2026-06-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_demandepiece_fiche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandepiece',
            name='statut',
            field=models.CharField(choices=[('demandee', 'Demandée'), ('hors_stock', 'Hors stock (A commander)'), ('en_attente_fournisseur', 'En attente fournisseur'), ('acceptee_fournisseur', 'Acceptée fournisseur'), ('refusee_fournisseur', 'Refusée fournisseur'), ('reaffectee', 'Réaffectée à un autre fournisseur'), ('commandee', 'Commandée'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='demandee', max_length=30),
        ),
    ]
